### ISSUE TITLE
Doesn't work or I haven't been able to set it up properly

### ISSUE THREAD

**Issue by Pastafarianist** [Exalm/gnome-shell-extension-workspace-switch-gesture#9]
I'm running Gnome 3.26.2 under Manjaro Linux. I installed this extension using

```
git clone git@github.com:Exalm/gnome-shell-extension-workspace-switch-gesture.git
cd gnome-shell-extension-workspace-switch-gesture
make install
```

Then I rebooted, went to https://extensions.gnome.org/local/ in Chrome, enabled the extension there and rebooted again.

Vertical swipe with 3 fingers works exactly as before, that is, the switch is only triggered after I lift my fingers.

On a freshly installed system, vertical 4-finger swipe on the touchpad had no effect (only the touchscreen swipe worked), so following some online tutorial I installed `libinput-gestures` (from AUR, version 2.32-1) and added my user to the `input` group. After that, the swipe started working.

I am on commit `f147f07cbab1219c06b24fadf80b22038d254670` (latest as of the moment of filing this issue).

**Comment by Exalm** [comment]
It's 3 fingers, not 4 fingers.

**Comment by Pastafarianist** [comment]
Yes, I realized that after submitting the issue, disabled the [Extended Gestures plugin](https://github.com/mpiannucci/gnome-shell-extended-gestures) which I had had installed and rebooted.
Still, 3-finger swipe switches workspaces, and does so only after I release the touch.

**Comment by Exalm** [comment]
Did you remove libinput-gestures?

**Comment by Pastafarianist** [comment]
No.

**Comment by Pastafarianist** [comment]
In any case, after removing `libinput-gestures` both 3- and 4-finger swipes stop working (with `workspace-switch-gesture` still being enabled).

**Comment by Exalm** [comment]
At least 4-finger swipe isn't related to this extension, it's a default GNOME Shell feature.
Are you on Wayland or X11?

**Comment by Pastafarianist** [comment]
Wayland.

Like I said, on a vanilla installation I only had touchscreen 4-finger swipe working. Furthermore, [here](https://wiki.gnome.org/Design/OS/Gestures) it is said that the touchpad has no gestures for workspace switching by default, unlike the touchscreen (waaat?..).

**Comment by Exalm** [comment]
From that page:
> last edited 2015-02-02 10:54:51

The gesture was added after that. :)
https://gitlab.gnome.org/GNOME/gnome-shell/commit/f3ecfab3783f4c1832ecf93e34a4cd414870e6c9

So, currently even default gesture doesn't work? That doesn't sound right, it should work regardless.
In this case the extension wouldn't work as well, as it uses exactly same mechanism.

Maybe the shell disables touchpad gestures if there's a touchscreen?.. Maybe something with udev, though in that case `libinput-gestures` wouldn't work as well. Did you install some udev rule along with that? Does `libinput debug-events` detect the gestures?

**Comment by Pastafarianist** [comment]
> Did you install some udev rule along with that? 

No, or at least I don't remember doing so.

> Does `libinput debug-events` detect the gestures?

After doing a 4-finger downwards swipe:

```
-event8   GESTURE_SWIPE_BEGIN  +6.49s	4
 event8   GESTURE_SWIPE_UPDATE  +6.49s	4  0.00/ 7.97 ( 0.00/28.71 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.50s	4  0.00/11.26 ( 0.00/30.35 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.51s	4  0.00/11.56 ( 0.00/31.17 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.51s	4  0.91/14.00 ( 2.46/37.73 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.52s	4  0.61/14.30 ( 1.64/38.55 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.53s	4  1.83/14.30 ( 4.92/38.55 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.54s	4  2.74/14.61 ( 7.38/39.37 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.54s	4  2.74/17.95 ( 7.38/48.39 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.55s	4  2.74/17.65 ( 7.38/47.57 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.56s	4  3.35/17.04 ( 9.02/45.93 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.57s	4  3.35/20.08 ( 9.02/54.13 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.57s	4  3.35/20.69 ( 9.02/55.77 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.58s	4  2.74/19.17 ( 7.38/51.67 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.59s	4  3.04/23.12 ( 8.20/62.34 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.59s	4  2.74/22.21 ( 7.38/59.88 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.60s	4  2.74/21.30 ( 7.38/57.41 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.61s	4  2.13/24.34 ( 5.74/65.62 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.62s	4  1.83/22.82 ( 4.92/61.52 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.62s	4  1.52/25.56 ( 4.10/68.90 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.63s	4  1.52/25.86 ( 4.10/69.72 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.64s	4  0.91/26.78 ( 2.46/72.18 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.65s	4  0.91/27.38 ( 2.46/73.82 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.65s	4  0.61/25.86 ( 1.64/69.72 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.66s	4  0.61/28.91 ( 1.64/77.92 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.67s	4  0.61/28.30 ( 1.64/76.28 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.67s	4  0.91/30.12 ( 2.46/81.20 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.68s	4  0.61/29.82 ( 1.64/80.38 unaccelerated)
 event8   GESTURE_SWIPE_UPDATE  +6.69s	4  0.00/19.78 ( 0.00/53.31 unaccelerated)
 event8   GESTURE_SWIPE_END  +6.71s	4
```

**Comment by Exalm** [comment]
There's also a 3-finger touchpad pinch for showing overview. Does that work?

**Comment by Pastafarianist** [comment]
Only with `libinput-gestures` enabled.
BTW, all of this happens on a Dell XPS 15 9560 laptop.

**Comment by Exalm** [comment]
Ok, so gnome-shell just doesn't detect any gestures. I have no idea why :/
Worth filing an issue at https://gitlab.gnome.org/GNOME/gnome-shell/issues?
(About the 4-finger swipe and 3-finger pinch, not about this extension)

**Comment by Pastafarianist** [comment]
Thank you. Submitted [here](https://gitlab.gnome.org/GNOME/gnome-shell/issues/68).

**Comment by Exalm** [comment]
Also, `libinput-gestures` is a script that reads `libinput-debug-events` output and performs actions based on that, so that isn't relevant at all ;)
